FROM ubuntu:14.04

# this is a base image with just python installed
# Update package
RUN apt-get -y update \ 
    && apt-get -y install software-properties-common \ 
    python-software-properties \
    build-essential

